import React, { useState, useEffect, useRef, useCallback } from "react";
import { WhatsAppConfig, SiteConfig } from "../types";
import { Cpu, Play, Square, Zap, TrendingUp, AlertTriangle, Send, Bot } from "lucide-react";

interface Props {
  config: WhatsAppConfig;
  siteConfig: SiteConfig;
  aiConfigured: boolean;
  onPostToWhatsApp: (text: string) => Promise<{ success: boolean; messageId?: string; error?: string }>;
  onSignalGenerated: (signal: any) => void;
}

interface Market {
  name: string;
  action: string;
  strategy: string;
  ticks: string;
  entryDigit: string;
  strength: number;
  trend: number[];
}

const MARKETS: Market[] = [
  { name: "VOLATILITY 10 INDEX",      action: "UNDER 7", strategy: "Second Least Digit",   ticks: "1ticks",  entryDigit: "9", strength: 0, trend: [] },
  { name: "VOLATILITY 25 INDEX",      action: "UNDER 7", strategy: "Second Least Digit",   ticks: "1ticks",  entryDigit: "9", strength: 0, trend: [] },
  { name: "VOLATILITY 50 INDEX",      action: "UNDER 7", strategy: "Digit Oscillator",     ticks: "3ticks",  entryDigit: "9", strength: 0, trend: [] },
  { name: "VOLATILITY 75 INDEX",      action: "OVER 2",  strategy: "Over Threshold",       ticks: "5ticks",  entryDigit: "1", strength: 0, trend: [] },
  { name: "VOLATILITY 100 INDEX",     action: "UNDER 8", strategy: "Second Least Digit",   ticks: "1ticks",  entryDigit: "9", strength: 0, trend: [] },
  { name: "VOLATILITY 100 (1s) INDEX",action: "UNDER 7", strategy: "High Freq Pattern",   ticks: "1ticks",  entryDigit: "9", strength: 0, trend: [] },
  { name: "JUMP 25 INDEX",            action: "OVER 3",  strategy: "Jump Breakout",        ticks: "5ticks",  entryDigit: "2", strength: 0, trend: [] },
  { name: "JUMP 50 INDEX",            action: "UNDER 6", strategy: "Reversal Pattern",     ticks: "3ticks",  entryDigit: "8", strength: 0, trend: [] },
];

function getSiteConfig(): SiteConfig {
  try {
    return JSON.parse(localStorage.getItem("wa_site_config") || "{}");
  } catch {
    return { siteName: "", promoUrl: "", botName: "BOT", botSignature: "Signal Bot", hashtags: "#TradingSignal", bots: [] };
  }
}

function buildSignalText(m: Market, cfg: SiteConfig): string {
  const now = new Date().toUTCString();
  const digitMap: Record<string, string> = { "UNDER 7": "9", "UNDER 8": "9", "UNDER 6": "8", "OVER 2": "1", "OVER 3": "2" };
  const digit = digitMap[m.action] || m.entryDigit;
  return (
    `🔔 *NEW TRADING SIGNAL* 🔔\n\n*${m.name.toUpperCase()}*\n\n` +
    `📈 *${m.action.toUpperCase()}*\n⚡ *Strategy:* ${m.strategy}\n\n` +
    `🎯 *Entry Instructions:*\n\n*${cfg.botName || "USE BOT"}*\n` +
    `💹 *Trade:* ${m.action}\n🔑 *Entry Digit:* \`${digit}\`\n⭐ *Confidence:* ${m.strength}%\n\n` +
    `${cfg.promoUrl || ""}\n\n` +
    `⚠️ *Risk Management:*\n• Stop after 4 consecutive wins\n• Max 5 runs per session\n• Use proper recovery if loss occurs\n\n` +
    `⏰ *Time:* ${now}\n\n🤖 _Generated by ${cfg.botSignature || "Signal Bot"}_\n${cfg.hashtags || "#TradingSignal"}`
  );
}

function buildAlertText(cfg: SiteConfig): string {
  return (
    `🚨 *ALERT TO ALL ${(cfg.siteName || "SIGNAL BOT").toUpperCase()} MEMBERS* 🚨\n\n` +
    `⚠ In just 1 minute, a new signal will be sent!\n📢 *Be ready and standby!*\n\n` +
    `🖥 *Go to:* ${cfg.promoUrl || ""}\n🤖 *Load your bot:* \`${cfg.botName || "BOT"}\`\n\n` +
    `✅ Make sure your settings are ready…\n🚀 Let's catch this trade together!\n\n` +
    `#StayAlert #${(cfg.siteName || "signal").replace(/\s+/g, "").toLowerCase()}signal 🔥📈\n` +
    `We either go home or go hard 💸\nNo risk no Ferrari 🚀\n${cfg.promoUrl || ""}`
  );
}

export default function ScannerView({ config, siteConfig, aiConfigured, onPostToWhatsApp, onSignalGenerated }: Props) {
  const [isRunning, setIsRunning] = useState(false);
  const [markets, setMarkets] = useState<Market[]>(MARKETS.map(m => ({ ...m, strength: 60 + Math.floor(Math.random() * 30), trend: Array.from({ length: 20 }, () => Math.random() * 100) })));
  const [log, setLog] = useState<{ time: string; msg: string; type: "info" | "success" | "warn" }[]>([]);
  const [signalsSent, setSignalsSent] = useState(0);
  const [lastSignal, setLastSignal] = useState<string | null>(null);
  const [broadcastMode, setBroadcastMode] = useState(true);
  const [aiMode, setAiMode] = useState(aiConfigured);
  const [threshold, setThreshold] = useState(85);

  const runnerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isRunningRef = useRef(false);

  const addLog = useCallback((msg: string, type: "info" | "success" | "warn" = "info") => {
    const time = new Date().toLocaleTimeString();
    setLog(prev => [{ time, msg, type }, ...prev].slice(0, 80));
  }, []);

  const simulateTick = useCallback(() => {
    setMarkets(prev => prev.map(m => {
      const delta = (Math.random() - 0.48) * 8;
      const newStr = Math.max(50, Math.min(99, m.strength + delta));
      const newTrend = [...m.trend.slice(-19), newStr];
      return { ...m, strength: Math.round(newStr), trend: newTrend };
    }));
  }, []);

  const checkAndBroadcast = useCallback(async () => {
    const cfg = getSiteConfig();
    setMarkets(prev => {
      const hot = prev.filter(m => m.strength >= threshold);
      if (hot.length === 0) return prev;
      const target = hot[Math.floor(Math.random() * hot.length)];

      (async () => {
        addLog(`🎯 Signal condition met: ${target.name} (${target.strength}%)`, "success");
        setLastSignal(target.name);

        if (!broadcastMode || !config.isConnected) {
          addLog("Draft mode — not broadcasting", "warn");
          return;
        }

        // Pre-signal alert
        addLog("📢 Sending standby alert...", "info");
        const alertText = buildAlertText(cfg);
        await onPostToWhatsApp(alertText);

        // Wait 60 seconds then send actual signal
        await new Promise(r => setTimeout(r, 60000));

        if (!isRunningRef.current) return;

        let signalText: string;
        if (aiMode && aiConfigured) {
          addLog("🤖 Generating AI signal...", "info");
          try {
            const res = await fetch("/api/gemini/generate-signal", {
              method: "POST", headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                symbol: target.name, action: target.action, isDerivStyle: true,
                strategyName: target.strategy, ticksCount: target.ticks,
                botName: cfg.botName, entryDigit: target.entryDigit, confidence: `${target.strength}%`,
                promoUrl: cfg.promoUrl, siteName: cfg.siteName, botSignature: cfg.botSignature,
                hashtags: cfg.hashtags,
              }),
            });
            const data = await res.json();
            signalText = data.signal || buildSignalText(target, cfg);
          } catch { signalText = buildSignalText(target, cfg); }
        } else {
          signalText = buildSignalText(target, cfg);
        }

        addLog(`📤 Sending signal to ${config.groupName || "group"}...`, "info");
        const result = await onPostToWhatsApp(signalText);
        if (result.success) {
          setSignalsSent(s => s + 1);
          addLog(`✅ Signal sent! MessageID: ${result.messageId}`, "success");
          onSignalGenerated({
            id: `sc_${Date.now()}`, assetClass: "Deriv Synthetic",
            symbol: target.name, action: target.action, entry: `Digit ${target.entryDigit}`,
            tp1: "", tp2: "", tp3: "", sl: `Confidence: ${target.strength}%`,
            userNotes: "", formattedText: signalText, rationale: `Auto-scan: ${target.strategy}`,
            status: "ACTIVE", sentMessageId: result.messageId || null,
            groupIdUsed: config.groupId, groupNameUsed: config.groupName,
            createdAt: new Date().toISOString(), updateHistory: [],
          });
        } else {
          addLog(`❌ Send failed: ${result.error}`, "warn");
        }
      })();

      return prev;
    });
  }, [threshold, broadcastMode, aiMode, aiConfigured, config, onPostToWhatsApp, onSignalGenerated, addLog]);

  // Main scan loop
  useEffect(() => {
    if (!isRunning) { isRunningRef.current = false; return; }
    isRunningRef.current = true;
    addLog("🟢 Scanner started — monitoring Deriv synthetic markets", "success");

    let tickCount = 0;
    const loop = () => {
      if (!isRunningRef.current) return;
      simulateTick();
      tickCount++;
      if (tickCount % 30 === 0) { // check every ~30 ticks
        checkAndBroadcast();
      }
      runnerRef.current = setTimeout(loop, 1500);
    };
    runnerRef.current = setTimeout(loop, 1500);
    return () => { if (runnerRef.current) clearTimeout(runnerRef.current); };
  }, [isRunning]);

  const toggleScanner = () => {
    if (isRunning) {
      isRunningRef.current = false;
      if (runnerRef.current) clearTimeout(runnerRef.current);
      addLog("🔴 Scanner stopped", "warn");
    }
    setIsRunning(v => !v);
  };

  return (
    <div className="space-y-4 animate-fade-in">
      {/* Controls */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Cpu className={`w-4 h-4 ${isRunning ? "text-emerald-400" : "text-slate-500"}`} />
            <span className="text-sm font-bold text-white">Market Scanner</span>
            {isRunning && <span className="text-[9px] font-bold text-emerald-300 bg-emerald-950/60 border border-emerald-900 px-2 py-0.5 rounded-full animate-pulse">LIVE</span>}
          </div>
          <button
            onClick={toggleScanner}
            className={`flex items-center gap-1.5 px-4 py-2 text-xs font-bold rounded-xl transition-all ${isRunning ? "bg-rose-600 hover:bg-rose-500 text-white" : "bg-emerald-600 hover:bg-emerald-500 text-white"}`}
          >
            {isRunning ? <><Square className="w-3.5 h-3.5" /> Stop</> : <><Play className="w-3.5 h-3.5" /> Start</>}
          </button>
        </div>

        <div className="grid grid-cols-3 gap-3 text-[11px]">
          <div className="space-y-1">
            <p className="text-slate-400">Min Strength</p>
            <div className="flex items-center gap-1.5">
              <input type="range" min={70} max={98} value={threshold} onChange={e => setThreshold(Number(e.target.value))} className="flex-1" />
              <span className="text-white font-bold w-8">{threshold}%</span>
            </div>
          </div>
          <label className="flex items-center gap-2 cursor-pointer">
            <div className={`relative w-8 h-4 rounded-full transition-colors ${broadcastMode ? "bg-emerald-500" : "bg-slate-700"}`} onClick={() => setBroadcastMode(v => !v)}>
              <span className={`absolute top-0.5 w-3 h-3 bg-white rounded-full shadow transition-transform ${broadcastMode ? "translate-x-4" : "translate-x-0.5"}`} />
            </div>
            <span className="text-slate-300">Auto-send</span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <div className={`relative w-8 h-4 rounded-full transition-colors ${aiMode ? "bg-sky-500" : "bg-slate-700"}`} onClick={() => setAiMode(v => !v)}>
              <span className={`absolute top-0.5 w-3 h-3 bg-white rounded-full shadow transition-transform ${aiMode ? "translate-x-4" : "translate-x-0.5"}`} />
            </div>
            <span className="text-slate-300">AI Mode</span>
          </label>
        </div>

        <div className="flex items-center gap-4 text-[11px] text-slate-500 border-t border-slate-800 pt-3">
          <span>Signals sent: <b className="text-white">{signalsSent}</b></span>
          {lastSignal && <span>Last: <b className="text-emerald-400">{lastSignal}</b></span>}
        </div>
      </div>

      {/* Market grid */}
      <div className="grid grid-cols-1 gap-2">
        {markets.map(m => {
          const hot = m.strength >= threshold;
          return (
            <div key={m.name} className={`bg-slate-900 border rounded-xl p-3 transition-all ${hot ? "border-emerald-800/60" : "border-slate-800"}`}>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-xs font-semibold text-slate-200">{m.name}</p>
                  <p className="text-[10px] text-slate-500">{m.action} · {m.strategy}</p>
                </div>
                <div className="text-right">
                  <p className={`text-sm font-bold ${hot ? "text-emerald-400" : "text-slate-400"}`}>{m.strength}%</p>
                  {hot && <span className="text-[8px] text-emerald-300 font-bold uppercase">Signal Ready</span>}
                </div>
              </div>
              {/* Mini sparkline */}
              <div className="mt-2 flex items-end gap-px h-6">
                {m.trend.slice(-20).map((v, i) => (
                  <div key={i} className={`flex-1 rounded-sm transition-all ${v >= threshold ? "bg-emerald-500" : "bg-slate-700"}`}
                    style={{ height: `${Math.max(2, (v / 100) * 24)}px` }} />
                ))}
              </div>
            </div>
          );
        })}
      </div>

      {/* Activity log */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-2">
        <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider">Activity Log</p>
        {log.length === 0 && <p className="text-xs text-slate-600 text-center py-4">Start the scanner to see activity here</p>}
        <div className="space-y-1 max-h-40 overflow-y-auto">
          {log.map((l, i) => (
            <div key={i} className="flex items-start gap-2 text-[10px]">
              <span className="text-slate-600 shrink-0">{l.time}</span>
              <span className={l.type === "success" ? "text-emerald-400" : l.type === "warn" ? "text-amber-400" : "text-slate-400"}>{l.msg}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
