import React, { useState } from "react";
import { WhatsAppConfig, SiteConfig } from "../types";
import { Send, Sparkles, Search, ChevronDown, Eye } from "lucide-react";

interface Props {
  config: WhatsAppConfig;
  siteConfig: SiteConfig;
  aiConfigured: boolean;
  onSiteConfigChange: (s: SiteConfig) => void;
  onPostToWhatsApp: (text: string) => Promise<{ success: boolean; messageId?: string; error?: string }>;
  onSignalSaved: (signal: any) => void;
}

type Mode = "deriv" | "forex";

const CONTRACTS = ["UNDER 7", "UNDER 8", "UNDER 6", "OVER 2", "OVER 3", "OVER 4"];

export default function SignalForm({ config, siteConfig, aiConfigured, onSiteConfigChange, onPostToWhatsApp, onSignalSaved }: Props) {
  const [mode, setMode] = useState<Mode>("deriv");

  // Deriv fields
  const [symbol, setSymbol]       = useState("VOLATILITY 100 INDEX");
  const [action, setAction]       = useState("UNDER 7");
  const [strategy, setStrategy]   = useState("Second Least Digit");
  const [ticks, setTicks]         = useState("1ticks");
  const [entryDigit, setEntryDigit] = useState("9");
  const [confidence, setConfidence] = useState("85%");
  const [notes, setNotes]         = useState("");

  // Forex fields
  const [fxSymbol, setFxSymbol]   = useState("XAUUSD");
  const [fxAction, setFxAction]   = useState("BUY");
  const [entry, setEntry]         = useState("");
  const [tp1, setTp1]             = useState("");
  const [tp2, setTp2]             = useState("");
  const [sl, setSl]               = useState("");

  // Preview
  const [preview, setPreview]     = useState("");
  const [rationale, setRationale] = useState("");

  // UI state
  const [generating, setGenerating]   = useState(false);
  const [sending, setSending]         = useState(false);
  const [sendResult, setSendResult]   = useState<{ ok: boolean; msg: string } | null>(null);

  // Site detection
  const [siteUrl, setSiteUrl]       = useState(siteConfig.promoUrl || "");
  const [detecting, setDetecting]   = useState(false);
  const [detectStatus, setDetectStatus] = useState("");
  const [detectedBots, setDetectedBots] = useState<string[]>(siteConfig.bots || []);
  const [showBotPicker, setShowBotPicker] = useState(false);

  const spinner = <svg className="animate-spin h-3.5 w-3.5" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>;

  // Detect site
  const handleDetect = async () => {
    if (!siteUrl.trim()) return;
    setDetecting(true); setDetectStatus(""); setShowBotPicker(false);
    try {
      const res  = await fetch("/api/site/detect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ siteUrl }) });
      const data = await res.json();
      if (!res.ok || !data.success) throw new Error(data.error);
      const safeName = (data.siteName || "").replace(/[^A-Za-z0-9\s]/g, "").trim();
      const newCfg: SiteConfig = {
        ...siteConfig,
        siteName: data.siteName,
        promoUrl: data.siteUrl,
        bots: data.bots || [],
        botSignature: `${data.siteName} Signal Bot`,
        hashtags: `#TradingSignal #${safeName.replace(/\s+/g, "")} #Signals`,
      };
      onSiteConfigChange(newCfg);
      setDetectedBots(data.bots || []);
      if (data.bots?.length === 1) {
        onSiteConfigChange({ ...newCfg, botName: `USE ${data.bots[0].toUpperCase()}` });
        setDetectStatus(`✅ "${data.siteName}" — 1 bot auto-selected`);
      } else if (data.bots?.length > 1) {
        setShowBotPicker(true);
        setDetectStatus(`✅ "${data.siteName}" — ${data.bots.length} bots found, pick one`);
      } else {
        setDetectStatus(`✅ "${data.siteName}" detected`);
      }
    } catch (err: any) { setDetectStatus(`❌ ${err.message}`); }
    finally { setDetecting(false); }
  };

  // Build WhatsApp signal text manually
  const buildManualText = (): string => {
    const cfg = siteConfig;
    if (mode === "deriv") {
      const digitMap: Record<string, string> = { "UNDER 7": "9", "UNDER 8": "9", "UNDER 6": "8", "OVER 2": "1", "OVER 3": "2", "OVER 4": "3" };
      return (
        `🔔 *NEW TRADING SIGNAL* 🔔\n\n*${symbol.toUpperCase()}*\n\n` +
        `📈 *${action.toUpperCase()}*\n⚡ *Strategy:* ${strategy}\n\n` +
        `🎯 *Entry Instructions:*\n\n*${cfg.botName || "USE BOT"}*\n` +
        `💹 *Trade:* ${action}\n🔑 *Entry Digit:* \`${digitMap[action] || entryDigit}\`\n⭐ *Confidence:* ${confidence}\n\n` +
        `${cfg.promoUrl || ""}\n\n` +
        `⚠️ *Risk Management:*\n• Stop after 4 consecutive wins\n• Max 5 runs per session\n• Use proper recovery if loss occurs\n\n` +
        `⏰ *Time:* ${new Date().toUTCString()}\n\n🤖 _Generated by ${cfg.botSignature || "Signal Bot"}_\n${cfg.hashtags || ""}`
      );
    } else {
      return (
        `📊 *FOREX/CRYPTO SIGNAL* 📊\n\n*${fxSymbol}*\n\n` +
        `📈 *${fxAction}*\n💰 *Entry:* ${entry || "Market"}\n` +
        `🎯 *TP1:* ${tp1 || "—"} | *TP2:* ${tp2 || "—"}\n🛑 *SL:* ${sl || "—"}\n\n` +
        `${cfg.promoUrl || ""}\n\n` +
        `⚠️ *Risk:* Never risk more than 2% per trade\n\n` +
        `⏰ *Time:* ${new Date().toUTCString()}\n🤖 _${cfg.botSignature || "Signal Bot"}_\n${cfg.hashtags || ""}`
      );
    }
  };

  const handleGenerate = async () => {
    if (!aiConfigured) { setPreview(buildManualText()); return; }
    setGenerating(true);
    try {
      const body = mode === "deriv"
        ? { symbol, action, isDerivStyle: true, strategyName: strategy, ticksCount: ticks, botName: siteConfig.botName, entryDigit, confidence, promoUrl: siteConfig.promoUrl, siteName: siteConfig.siteName, botSignature: siteConfig.botSignature, hashtags: siteConfig.hashtags, userNotes: notes }
        : { symbol: fxSymbol, action: fxAction, assetClass: "Forex", entry, tp: [tp1, tp2], sl, userNotes: notes, isDerivStyle: false, botSignature: siteConfig.botSignature, hashtags: siteConfig.hashtags };
      const res  = await fetch("/api/gemini/generate-signal", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const data = await res.json();
      setPreview(data.signal || buildManualText());
      setRationale(data.rationale || "");
    } catch { setPreview(buildManualText()); }
    finally { setGenerating(false); }
  };

  const handleSend = async () => {
    const text = preview || buildManualText();
    if (!text) return;
    setSending(true); setSendResult(null);
    const result = await onPostToWhatsApp(text);
    setSendResult({ ok: result.success, msg: result.success ? `Sent! ID: ${result.messageId}` : result.error || "Send failed" });
    if (result.success) {
      onSignalSaved({
        id: `sig_${Date.now()}`, assetClass: mode === "deriv" ? "Deriv Synthetic" : "Forex",
        symbol: mode === "deriv" ? symbol : fxSymbol, action: mode === "deriv" ? action : fxAction,
        entry: mode === "deriv" ? `Digit ${entryDigit}` : entry, tp1, tp2, tp3: "", sl,
        userNotes: notes, formattedText: text, rationale,
        status: "ACTIVE", sentMessageId: result.messageId || null,
        groupIdUsed: config.groupId, groupNameUsed: config.groupName,
        createdAt: new Date().toISOString(), updateHistory: [],
      });
    }
    setSending(false);
  };

  return (
    <div className="space-y-4 animate-fade-in">
      {/* Site detection */}
      <div className="bg-slate-900 border border-sky-900/30 rounded-2xl p-4 space-y-3">
        <p className="text-[10px] font-semibold text-sky-400 uppercase tracking-wider">Linked Trading Site</p>
        <div className="flex gap-2">
          <input type="url" value={siteUrl} onChange={e => { setSiteUrl(e.target.value); onSiteConfigChange({ ...siteConfig, promoUrl: e.target.value }); }}
            placeholder="https://yoursite.com" className="flex-1 px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-sky-300 placeholder-slate-600 outline-none font-mono" />
          <button onClick={handleDetect} disabled={detecting || !siteUrl.trim()}
            className="flex items-center gap-1.5 px-3 py-2 bg-sky-600 hover:bg-sky-500 disabled:bg-slate-800 disabled:text-slate-500 text-white text-xs font-bold rounded-xl transition-all">
            {detecting ? spinner : <Search className="w-3.5 h-3.5" />}
            {detecting ? "Detecting..." : "Detect"}
          </button>
        </div>
        {detectStatus && <p className="text-[11px] text-slate-300">{detectStatus}</p>}
        {showBotPicker && detectedBots.length > 1 && (
          <div className="bg-slate-950 border border-slate-800 rounded-xl overflow-hidden">
            <p className="text-[10px] text-slate-400 px-3 py-2 border-b border-slate-800 font-semibold">Select bot:</p>
            {detectedBots.map((b, i) => (
              <button key={i} onClick={() => { onSiteConfigChange({ ...siteConfig, botName: `USE ${b.toUpperCase()}` }); setShowBotPicker(false); setDetectStatus(`✅ Bot: "${b}" selected`); }}
                className="w-full text-left px-3 py-2.5 hover:bg-slate-800 text-xs text-amber-300 font-semibold transition-colors">
                {b}
              </button>
            ))}
          </div>
        )}
        {siteConfig.siteName && (
          <div className="flex flex-wrap gap-2 text-[10px]">
            <span className="bg-slate-800 text-white px-2 py-0.5 rounded font-medium">{siteConfig.siteName}</span>
            {siteConfig.botName && <span className="bg-slate-800 text-amber-300 px-2 py-0.5 rounded font-mono">{siteConfig.botName}</span>}
          </div>
        )}
      </div>

      {/* Mode toggle */}
      <div className="flex gap-2">
        {(["deriv", "forex"] as Mode[]).map(m => (
          <button key={m} onClick={() => setMode(m)}
            className={`flex-1 py-2 text-xs font-bold rounded-xl transition-all capitalize ${mode === m ? "bg-emerald-600 text-white" : "bg-slate-800 text-slate-400 hover:text-white"}`}>
            {m === "deriv" ? "Deriv Synthetic" : "Forex / Crypto"}
          </button>
        ))}
      </div>

      {/* Form fields */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 space-y-3">
        {mode === "deriv" ? (
          <>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Index</label>
                <input value={symbol} onChange={e => setSymbol(e.target.value)} className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-slate-100 outline-none" /></div>
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Contract</label>
                <select value={action} onChange={e => setAction(e.target.value)} className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-slate-100 outline-none">
                  {CONTRACTS.map(c => <option key={c}>{c}</option>)}</select></div>
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Strategy</label>
                <input value={strategy} onChange={e => setStrategy(e.target.value)} className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-slate-100 outline-none" /></div>
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Confidence</label>
                <input value={confidence} onChange={e => setConfidence(e.target.value)} className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-emerald-400 outline-none font-bold text-center" /></div>
            </div>
          </>
        ) : (
          <>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Symbol</label>
                <input value={fxSymbol} onChange={e => setFxSymbol(e.target.value)} className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-slate-100 outline-none font-mono" /></div>
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Direction</label>
                <select value={fxAction} onChange={e => setFxAction(e.target.value)} className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-slate-100 outline-none">
                  <option>BUY</option><option>SELL</option></select></div>
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Entry</label>
                <input value={entry} onChange={e => setEntry(e.target.value)} placeholder="e.g. 2345.50" className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-slate-100 outline-none" /></div>
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Stop Loss</label>
                <input value={sl} onChange={e => setSl(e.target.value)} placeholder="e.g. 2330.00" className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-rose-400 outline-none" /></div>
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Take Profit 1</label>
                <input value={tp1} onChange={e => setTp1(e.target.value)} placeholder="TP1" className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-emerald-400 outline-none" /></div>
              <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Take Profit 2</label>
                <input value={tp2} onChange={e => setTp2(e.target.value)} placeholder="TP2" className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-emerald-400 outline-none" /></div>
            </div>
          </>
        )}
        <div className="space-y-1"><label className="text-[10px] text-slate-400 font-medium">Additional Notes (optional)</label>
          <textarea value={notes} onChange={e => setNotes(e.target.value)} rows={2} placeholder="Any extra context..." className="w-full px-2.5 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-emerald-500 rounded-lg text-slate-100 outline-none resize-none" /></div>
      </div>

      {/* Generate / preview */}
      <div className="flex gap-2">
        <button onClick={handleGenerate} disabled={generating}
          className="flex-1 flex items-center justify-center gap-1.5 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold rounded-xl transition-all disabled:opacity-50">
          {generating ? spinner : <Sparkles className="w-3.5 h-3.5 text-amber-400" />}
          {generating ? "Generating..." : aiConfigured ? "AI Generate & Preview" : "Build & Preview"}
        </button>
      </div>

      {preview && (
        <div className="bg-slate-950 border border-slate-800 rounded-2xl p-4 space-y-3">
          <div className="flex items-center gap-1.5">
            <Eye className="w-3.5 h-3.5 text-slate-400" />
            <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider">Signal Preview (WhatsApp format)</p>
          </div>
          <pre className="text-[11px] text-slate-200 whitespace-pre-wrap leading-relaxed font-sans">{preview}</pre>
          {rationale && <p className="text-[10px] text-slate-500 border-t border-slate-800 pt-2"><b className="text-slate-400">Rationale:</b> {rationale}</p>}
        </div>
      )}

      {sendResult && (
        <div className={`text-[11px] px-3 py-2.5 rounded-xl border ${sendResult.ok ? "bg-emerald-950/30 border-emerald-900/30 text-emerald-400" : "bg-rose-950/30 border-rose-900/30 text-rose-400"}`}>
          {sendResult.msg}
        </div>
      )}

      <button onClick={handleSend} disabled={sending || !config.isConnected}
        className="w-full flex items-center justify-center gap-2 py-3 bg-emerald-600 hover:bg-emerald-500 disabled:bg-slate-800 disabled:text-slate-500 text-white font-bold text-sm rounded-2xl transition-all">
        {sending ? spinner : <Send className="w-4 h-4" />}
        {sending ? "Sending..." : config.isConnected ? "Send to WhatsApp" : "Connect a group first"}
      </button>
    </div>
  );
}
