import React, { useState } from "react";
import { SiteConfig } from "../types";
import { FolderOpen, Send, Copy, Check, Zap } from "lucide-react";

interface Props {
  siteConfig: SiteConfig;
  onPostToWhatsApp: (text: string) => Promise<{ success: boolean; messageId?: string; error?: string }>;
}

function buildTemplate(type: string, cfg: SiteConfig): string {
  const now = new Date().toUTCString();
  const site = cfg.siteName || "Signal Bot";
  const bot  = cfg.botName  || "USE BOT";
  const url  = cfg.promoUrl || "";
  const sig  = cfg.botSignature || "Signal Bot";
  const tags = cfg.hashtags || "#TradingSignal";

  switch (type) {
    case "alert":
      return `🚨 *ALERT TO ALL ${site.toUpperCase()} MEMBERS* 🚨\n\n⚠ In just 1 minute, a new signal will be sent!\n📢 *Be ready and standby!*\n\n🖥 *Go to:* ${url}\n🤖 *Load your bot:* \`${bot}\`\n\n✅ Make sure your settings are ready…\n🚀 Let's catch this trade together!\n\n#StayAlert #${site.replace(/\s+/g, "").toLowerCase()}signal 🔥📈\nNo risk no Ferrari 🚀\n${url}`;
    case "vol100_under7":
      return `🔔 *NEW TRADING SIGNAL* 🔔\n\n*VOLATILITY 100 INDEX*\n\n📈 *UNDER 7*\n⚡ *Strategy:* Second Least Digit\n\n🎯 *Entry Instructions:*\n\n*${bot}*\n💹 *Trade:* UNDER 7\n🔑 *Entry Digit:* \`9\`\n⭐ *Confidence:* 87%\n\n${url}\n\n⚠️ *Risk Management:*\n• Stop after 4 consecutive wins\n• Max 5 runs per session\n• Use proper recovery if loss occurs\n\n⏰ *Time:* ${now}\n\n🤖 _Generated by ${sig}_\n${tags}`;
    case "vol75_over2":
      return `🔔 *NEW TRADING SIGNAL* 🔔\n\n*VOLATILITY 75 INDEX*\n\n📈 *OVER 2*\n⚡ *Strategy:* Over Threshold\n\n🎯 *Entry Instructions:*\n\n*${bot}*\n💹 *Trade:* OVER 2\n🔑 *Entry Digit:* \`1\`\n⭐ *Confidence:* 89%\n\n${url}\n\n⚠️ *Risk Management:*\n• Stop after 4 consecutive wins\n• Max 5 runs per session\n\n⏰ *Time:* ${now}\n\n🤖 _Generated by ${sig}_\n${tags}`;
    case "cooldown":
      return `⌛ *COOLDOWN & NEXT SIGNAL READY* ⌛\n\n✅ Previous alert sequence finalized!\n📡 _Entering temporary cooldown. Relax and prepare._\n\n🔔 *Stay tuned!* We are already scanning for the next opportunity.\n\n${url}`;
    case "session_open":
      return `🟢 *TRADING SESSION OPEN* 🟢\n\n📊 Markets are active and signals are incoming!\n\n🖥 *Platform:* ${url}\n🤖 *Bot:* \`${bot}\`\n\n⚡ Stay focused, manage your risk, and let's make some profits!\n\n#SessionOpen #${site.replace(/\s+/g, "")} 💰`;
    case "session_close":
      return `🔴 *TRADING SESSION CLOSED* 🔴\n\nGreat trading session everyone! 🎉\n\nSee you in the next session.\nKeep managing your risk and stay disciplined 💪\n\n${url}`;
    case "win":
      return `🏆 *WINNING SIGNAL!* 🏆\n\n✅ Our last signal was a *WIN!*\n\n📈 Keep the momentum going!\n🤖 Bot: \`${bot}\`\n\nStay ready for the next alert 🔔\n${url}\n\n💸 _${sig}_`;
    case "recovery":
      return `🔄 *RECOVERY MODE ACTIVATED* 🔄\n\nDon't worry — losses are part of the game.\n\n📊 *Recovery Strategy:* Martingale x2.1\n⚠️ Adjust your stake and stay disciplined.\n\nWe recover together 💪\n\n${url}`;
    default:
      return "";
  }
}

const TEMPLATES = [
  { id: "alert",         label: "Pre-Signal Alert",    desc: "Send 1 minute before signal",     icon: "🚨", color: "border-amber-900/40 bg-amber-950/20" },
  { id: "vol100_under7", label: "VOL 100 UNDER 7",     desc: "Ready-made Volatility 100 signal", icon: "📈", color: "border-emerald-900/40 bg-emerald-950/20" },
  { id: "vol75_over2",   label: "VOL 75 OVER 2",       desc: "Ready-made Volatility 75 signal",  icon: "📊", color: "border-sky-900/40 bg-sky-950/20" },
  { id: "cooldown",      label: "Cooldown Message",    desc: "Post-signal cooldown notice",      icon: "⌛", color: "border-slate-700 bg-slate-900" },
  { id: "session_open",  label: "Session Open",        desc: "Start of trading session",         icon: "🟢", color: "border-emerald-900/40 bg-emerald-950/20" },
  { id: "session_close", label: "Session Close",       desc: "End of trading session",           icon: "🔴", color: "border-rose-900/40 bg-rose-950/20" },
  { id: "win",           label: "Win Announcement",    desc: "Celebrate a winning signal",       icon: "🏆", color: "border-yellow-900/40 bg-yellow-950/20" },
  { id: "recovery",      label: "Recovery Mode",       desc: "After a losing signal",            icon: "🔄", color: "border-orange-900/40 bg-orange-950/20" },
];

export default function TemplatesView({ siteConfig, onPostToWhatsApp }: Props) {
  const [sending, setSending]       = useState<string | null>(null);
  const [copied, setCopied]         = useState<string | null>(null);
  const [results, setResults]       = useState<Record<string, boolean>>({});
  const [previewing, setPreviewing] = useState<string | null>(null);

  const handleSend = async (id: string) => {
    setSending(id);
    const text   = buildTemplate(id, siteConfig);
    const result = await onPostToWhatsApp(text);
    setResults(prev => ({ ...prev, [id]: result.success }));
    setSending(null);
  };

  const handleCopy = (id: string) => {
    navigator.clipboard.writeText(buildTemplate(id, siteConfig));
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  const spinner = <svg className="animate-spin h-3 w-3" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>;

  return (
    <div className="space-y-5 animate-fade-in">
      <div className="flex items-center gap-2">
        <FolderOpen className="w-5 h-5 text-slate-400" />
        <h2 className="text-base font-bold text-white">Signal Templates</h2>
      </div>

      {!siteConfig.siteName && (
        <div className="bg-amber-950/30 border border-amber-900/40 rounded-xl p-3 text-xs text-amber-300">
          ⚠️ Detect your site first (in the Compose tab) so templates include your site name and bot.
        </div>
      )}

      <div className="grid grid-cols-1 gap-3">
        {TEMPLATES.map(t => (
          <div key={t.id} className={`border rounded-2xl p-4 space-y-3 transition-all ${t.color}`}>
            <div className="flex items-start justify-between gap-2">
              <div className="flex items-start gap-2.5">
                <span className="text-xl leading-none">{t.icon}</span>
                <div>
                  <p className="text-xs font-bold text-white">{t.label}</p>
                  <p className="text-[10px] text-slate-400">{t.desc}</p>
                </div>
              </div>
              {results[t.id] !== undefined && (
                <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full border ${results[t.id] ? "text-emerald-400 border-emerald-900 bg-emerald-950/40" : "text-rose-400 border-rose-900 bg-rose-950/40"}`}>
                  {results[t.id] ? "Sent ✓" : "Failed"}
                </span>
              )}
            </div>

            {previewing === t.id && (
              <pre className="text-[10px] text-slate-300 bg-slate-950 border border-slate-800 rounded-lg p-3 whitespace-pre-wrap leading-relaxed max-h-40 overflow-y-auto">
                {buildTemplate(t.id, siteConfig)}
              </pre>
            )}

            <div className="flex gap-2">
              <button
                onClick={() => setPreviewing(prev => prev === t.id ? null : t.id)}
                className="flex items-center gap-1 px-2.5 py-1.5 text-[10px] text-slate-400 hover:text-white bg-slate-900/60 hover:bg-slate-800 rounded-lg transition-all"
              >
                <Zap className="w-3 h-3" />
                {previewing === t.id ? "Hide" : "Preview"}
              </button>
              <button
                onClick={() => handleCopy(t.id)}
                className="flex items-center gap-1 px-2.5 py-1.5 text-[10px] text-slate-400 hover:text-white bg-slate-900/60 hover:bg-slate-800 rounded-lg transition-all"
              >
                {copied === t.id ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                {copied === t.id ? "Copied!" : "Copy"}
              </button>
              <button
                onClick={() => handleSend(t.id)}
                disabled={sending === t.id}
                className="ml-auto flex items-center gap-1.5 px-3 py-1.5 text-[10px] font-bold bg-emerald-700 hover:bg-emerald-600 disabled:bg-slate-700 disabled:text-slate-500 text-white rounded-lg transition-all"
              >
                {sending === t.id ? spinner : <Send className="w-3 h-3" />}
                {sending === t.id ? "Sending..." : "Send Now"}
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
