import express from "express";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
app.use(express.json());

// ─── Gemini AI ────────────────────────────────────────────────────────────────
const ai = process.env.GEMINI_API_KEY
  ? new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })
  : null;

// ─── Whapi.Cloud helper ───────────────────────────────────────────────────────
// Whapi.Cloud is the API layer that lets you send messages to WhatsApp groups
// from any regular WhatsApp number — no Meta business verification required.
// Docs: https://whapi.cloud/docs
const WHAPI_BASE = "https://gate.whapi.cloud";

async function whapiRequest(
  endpoint: string,
  method: "GET" | "POST" | "PUT" | "DELETE",
  body?: object,
  token?: string
): Promise<any> {
  const apiToken = token || process.env.WHAPI_TOKEN;
  if (!apiToken) throw new Error("WHAPI_TOKEN is not set. Add it to Vercel environment variables.");

  const res = await fetch(`${WHAPI_BASE}${endpoint}`, {
    method,
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiToken}`,
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });

  const ct = res.headers.get("content-type") || "";
  if (!ct.includes("application/json")) {
    const txt = await res.text().catch(() => "(unreadable)");
    throw new Error(`Whapi returned non-JSON (HTTP ${res.status}). Preview: ${txt.substring(0, 200)}`);
  }

  return res.json();
}

// ─── Group ID sanitizer ──────────────────────────────────────────────────────
// Whapi requires group IDs to end with @g.us — e.g. 120363XXXXXXXXXX@g.us
// Without this suffix the message is sent to nowhere and appears to succeed.
function sanitizeGroupId(groupId: string): string {
  if (!groupId) return groupId;
  const clean = groupId.trim().replace(/\s+/g, "");
  // Already has the correct suffix
  if (clean.endsWith("@g.us")) return clean;
  // Has a different suffix — replace it
  if (clean.includes("@")) return clean.split("@")[0] + "@g.us";
  // Plain numeric ID — add the suffix
  return clean + "@g.us";
}

// ─── Signal formatting helpers ────────────────────────────────────────────────
// WhatsApp uses *bold*, _italic_, ~strikethrough~, ```code``` for formatting
function formatSignalForWhatsApp(params: {
  siteName: string;
  botName: string;
  promoUrl: string;
  market: string;
  contract: string;
  strategy: string;
  entryDigit: string;
  confidence: number;
  hashtags: string;
  botSignature: string;
}): string {
  const { siteName, botName, promoUrl, market, contract, strategy, entryDigit, confidence, hashtags, botSignature } = params;
  const now = new Date().toUTCString();
  return (
    `🔔 *NEW TRADING SIGNAL* 🔔\n\n` +
    `*${market.toUpperCase()}*\n\n` +
    `📈 *${contract.toUpperCase()}*\n` +
    `⚡ *Strategy:* ${strategy}\n\n` +
    `🎯 *Entry Instructions:*\n\n` +
    `*${botName}*\n` +
    `💹 *Trade:* ${contract}\n` +
    `🔑 *Entry Digit:* \`${entryDigit}\`\n` +
    `⭐ *Confidence:* ${confidence}%\n\n` +
    `${promoUrl}\n\n` +
    `⚠️ *Risk Management:*\n` +
    `• Stop after 4 consecutive wins\n• Max 5 runs per session\n• Use proper recovery if loss occurs\n\n` +
    `⏰ *Time:* ${now}\n\n` +
    `🤖 _Generated by ${botSignature}_\n` +
    `${hashtags}`
  );
}

function formatAlertForWhatsApp(params: {
  siteName: string;
  botName: string;
  promoUrl: string;
}): string {
  const { siteName, botName, promoUrl } = params;
  return (
    `🚨 *ALERT TO ALL ${siteName.toUpperCase()} MEMBERS* 🚨\n\n` +
    `⚠ In just 1 minute, a new signal will be sent!\n` +
    `📢 *Be ready and standby!*\n\n` +
    `🖥 *Go to:* ${promoUrl}\n` +
    `🤖 *Load your bot:* \`${botName}\`\n\n` +
    `✅ Make sure your settings are ready…\n` +
    `🚀 Let's catch this trade together!\n\n` +
    `#StayAlert #${siteName.replace(/\s+/g, "").toLowerCase()}signal 🔥📈\n` +
    `We either go home or go hard 💸\n` +
    `No risk no Ferrari 🚀\n` +
    promoUrl
  );
}

// ─── Routes ───────────────────────────────────────────────────────────────────

app.get("/api/health", (_req, res) => {
  res.json({
    status: "ok",
    timestamp: new Date().toISOString(),
    aiConfigured: !!ai,
    whapiConfigured: !!process.env.WHAPI_TOKEN,
  });
});

// ── Auth ──────────────────────────────────────────────────────────────────────
app.post("/api/login", (req, res) => {
  const { username, password } = req.body || {};
  const u = (typeof username === "string" ? username : "").trim();
  const p = (typeof password === "string" ? password : "").trim();
  const targetU = (process.env.ADMIN_USERNAME || "admin").trim();
  const targetP = (process.env.ADMIN_PASSWORD || "password").trim();

  const ok = (u === targetU || u.toLowerCase() === "admin") && p === targetP;
  if (ok) {
    res.json({ success: true, token: "wa_session_" + Buffer.from(u + ":" + Date.now()).toString("base64") });
  } else {
    res.status(401).json({ success: false, error: "Invalid username or password." });
  }
});

// ── WhatsApp: get groups the connected account is in ─────────────────────────
app.post("/api/whatsapp/groups", async (req, res) => {
  const { apiToken } = req.body;
  try {
    const data = await whapiRequest("/groups?count=100&offset=0", "GET", undefined, apiToken);
    // Whapi returns groups array; each group has id, subject (name), size (member count)
    const rawGroups = data.groups || data.items || [];
    const groups = rawGroups.map((g: any) => ({
      id: g.id,                                         // e.g. 120363XXXXXXXXXX@g.us
      name: g.subject || g.name || g.id,               // Whapi uses "subject" for group name
      participants: g.size || g.participants_count || 0,
      isAdmin: g.is_admin || false,
    }));
    res.json({ success: true, groups });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// ── WhatsApp: verify account / get account info ───────────────────────────────
app.post("/api/whatsapp/verify", async (req, res) => {
  const { apiToken } = req.body;
  if (!apiToken) {
    res.status(400).json({ error: "apiToken is required" });
    return;
  }
  try {
    const data = await whapiRequest("/settings", "GET", undefined, apiToken);
    res.json({
      success: true,
      phone: data.me?.phone || data.phone || "Unknown",
      name: data.me?.name || data.name || "WhatsApp Account",
      status: data.status || "connected",
    });
  } catch (err: any) {
    res.status(400).json({ success: false, error: err.message });
  }
});

// ── WhatsApp: send a message to a group ──────────────────────────────────────
app.post("/api/whatsapp/send", async (req, res) => {
  const { apiToken, groupId, text } = req.body;
  if (!apiToken || !groupId || !text) {
    res.status(400).json({ error: "apiToken, groupId, and text are required" });
    return;
  }

  // CRITICAL: ensure the group ID has the @g.us suffix Whapi requires
  const cleanGroupId = sanitizeGroupId(groupId);

  try {
    const data = await whapiRequest("/messages/text", "POST", {
      to: cleanGroupId,
      body: text,
    }, apiToken);

    // Whapi returns { sent: true, message: { id: "..." } } on success
    // or { error: { message: "..." } } / { message: "error text" } on failure
    if (data.error) {
      throw new Error(
        typeof data.error === "string" ? data.error :
        data.error?.message || data.error?.text || JSON.stringify(data.error)
      );
    }
    if (!data.sent && !data.message?.id && !data.id) {
      throw new Error(
        typeof data.message === "string" ? data.message : "Message not sent — check your group ID and API token"
      );
    }

    res.json({ success: true, messageId: data.message?.id || data.id || "sent" });
  } catch (err: any) {
    console.error("[WhatsApp/send]", err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

// ── WhatsApp: send test message ───────────────────────────────────────────────
app.post("/api/whatsapp/test", async (req, res) => {
  const { apiToken, groupId, groupName, siteName, botName, promoUrl } = req.body;
  if (!apiToken || !groupId) {
    res.status(400).json({ error: "apiToken and groupId are required" });
    return;
  }

  try {
    const text =
      `✅ *WhatsApp Signal Bot Connected!*\n\n` +
      `Your dashboard is now linked to *${groupName || groupId}*.\n` +
      `Trading alerts will be delivered here automatically.\n\n` +
      `📊 Site: ${siteName || "your site"}\n` +
      `🤖 Bot: ${botName || "configured bot"}\n` +
      `🔗 Link: ${promoUrl || ""}\n\n` +
      `⏰ _Verified: ${new Date().toUTCString()}_`;

    const cleanGroupId = sanitizeGroupId(groupId);
    const data = await whapiRequest("/messages/text", "POST", {
      to: cleanGroupId,
      body: text,
    }, apiToken);

    if (data.error) {
      throw new Error(
        typeof data.error === "string" ? data.error :
        data.error?.message || data.error?.text || JSON.stringify(data.error)
      );
    }
    if (!data.sent && !data.message?.id && !data.id) {
      throw new Error(
        typeof data.message === "string" ? data.message :
        `Message not delivered. Group ID used: ${cleanGroupId}. Make sure the ID ends with @g.us and your number is a member of the group.`
      );
    }

    res.json({ success: true, messageId: data.message?.id || data.id || "sent", groupName: groupName || groupId });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// ── WhatsApp: delete a message (auto-delete after N minutes) ─────────────────
app.post("/api/whatsapp/delete", async (req, res) => {
  const { apiToken, messageId } = req.body;
  if (!apiToken || !messageId) {
    res.status(400).json({ error: "apiToken and messageId are required" });
    return;
  }
  try {
    await whapiRequest(`/messages/${messageId}`, "DELETE", undefined, apiToken);
    res.json({ success: true });
  } catch (err: any) {
    // Already deleted = fine
    res.json({ success: true, note: err.message });
  }
});

// ── Gemini AI: generate trading signal ───────────────────────────────────────
app.post("/api/gemini/generate-signal", async (req, res) => {
  if (!ai) {
    res.status(500).json({ error: "Gemini AI not configured. Add GEMINI_API_KEY to Vercel environment variables." });
    return;
  }

  const {
    symbol, action, isDerivStyle = false,
    strategyName = "Second Least Digit", ticksCount = "1ticks",
    botName = "USE KICKTRADE BOT", entryDigit = "9", confidence = "85%",
    promoUrl = "", siteName = "", botSignature = "", hashtags = "",
    riskGuidelines = "• Stop after 4 consecutive wins\n• Max 5 runs per session\n• Use proper recovery if loss occurs",
    assetClass, entry, tp, sl, userNotes, sentiment = "Moderate",
  } = req.body;

  if (!symbol || !action) {
    res.status(400).json({ error: "Symbol and Action are required" });
    return;
  }

  // WhatsApp formatting uses *bold* _italic_ instead of HTML
  const prompt = isDerivStyle
    ? `Generate a premium WhatsApp trading signal for Deriv synthetic markets.
Use WhatsApp formatting: *bold*, _italic_, \`code\`.
INDEX: ${symbol} | ACTION: ${action} | STRATEGY: ${strategyName}
TICKS: ${ticksCount} | BOT: ${botName} | DIGIT: ${entryDigit} | CONFIDENCE: ${confidence}
SITE: ${siteName} | PROMO: ${promoUrl} | SIGNATURE: ${botSignature} | TAGS: ${hashtags}
RISK:\n${riskGuidelines}
NOTES: ${userNotes || "None"}
Output ONLY JSON: {"signal":"...","rationale":"..."}`
    : `Generate a professional WhatsApp trading signal.
Use WhatsApp formatting: *bold*, _italic_, \`code\`.
ASSET: ${assetClass || "Crypto/Forex"} | SYMBOL: ${symbol} | ACTION: ${action}
ENTRY: ${entry || "Market"} | SL: ${sl || "None"}
TPS: ${Array.isArray(tp) ? tp.filter(Boolean).join(", ") : "None"}
NOTES: ${userNotes || "None"} | RISK: ${sentiment}
Output ONLY JSON: {"signal":"...","rationale":"..."}`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: "OBJECT" as any,
          properties: {
            signal: { type: "STRING" as any },
            rationale: { type: "STRING" as any },
          },
          required: ["signal", "rationale"],
        },
      },
    });
    const raw = (response.text || "").trim().replace(/```json|```/g, "").trim();
    res.json(JSON.parse(raw));
  } catch (err: any) {
    res.status(500).json({ error: "Gemini generation failed", details: err.message });
  }
});

// ── Site detection: scrape linked site to detect name and bots ───────────────
app.post("/api/site/detect", async (req, res) => {
  const { siteUrl } = req.body;
  if (!siteUrl) { res.status(400).json({ error: "siteUrl is required" }); return; }

  let url = siteUrl.trim();
  if (!url.startsWith("http")) url = "https://" + url;

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10000);
    const response = await fetch(url, {
      signal: controller.signal,
      headers: { "User-Agent": "Mozilla/5.0 (compatible; SignalBot/1.0)", Accept: "text/html" },
    });
    clearTimeout(timeout);
    const html = await response.text();

    let siteName = "";
    const titleMatch = html.match(/<title[^>]*>([^<]{1,120})<\/title>/i);
    if (titleMatch) siteName = titleMatch[1].replace(/\s+/g, " ").trim();
    const ogMatch = html.match(/<meta[^>]+property=["']og:site_name["'][^>]+content=["']([^"']{1,80})["']/i);
    if (ogMatch) siteName = ogMatch[1].trim();
    if (!siteName) { try { siteName = new URL(url).hostname.replace(/^www\./, ""); } catch { siteName = url; } }

    const botPatterns = [
      /\b([A-Z][a-zA-Z0-9\s]{2,30}(?:Bot|Robot|Trader|EA|Signal|Auto|Sniper|Killer|Hunter|Scanner))\b/g,
      /\b([A-Z][A-Z0-9\s]{3,40}(?:BOT|ROBOT|TRADER|SIGNAL|SNIPER|KILLER))\b/g,
    ];
    const rawBots = new Set<string>();
    const plain = html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ");
    for (const pattern of botPatterns) {
      pattern.lastIndex = 0;
      let m;
      while ((m = pattern.exec(plain)) !== null) {
        const c = m[1].trim();
        if (c.length > 3 && c.length < 60) rawBots.add(c);
      }
    }
    const bots = Array.from(rawBots)
      .filter((b, _, arr) => !arr.some(o => o !== b && o.toLowerCase().includes(b.toLowerCase()) && o.length > b.length))
      .slice(0, 10);

    res.json({ success: true, siteUrl: url, siteName, bots, botCount: bots.length });
  } catch (err: any) {
    res.status(err.name === "AbortError" ? 408 : 500).json({
      error: err.name === "AbortError" ? "Site timed out." : `Failed to reach site: ${err.message}`,
    });
  }
});

// ── Auto-broadcast cron endpoint (stateless — config in request body) ─────────
// Called by cron-job.org every N minutes. Two separate cron jobs:
//   type:"alert"  → sends the pre-signal warning
//   type:"signal" → sends the actual trading signal (1 min later)
const MARKET_NAMES = [
  "VOLATILITY 10 INDEX", "VOLATILITY 25 INDEX", "VOLATILITY 50 INDEX",
  "VOLATILITY 75 INDEX", "VOLATILITY 100 INDEX", "VOLATILITY 100 (1s) INDEX",
  "VOLATILITY 75 (1s) INDEX", "VOLATILITY 50 (1s) INDEX",
  "JUMP 25 INDEX", "JUMP 50 INDEX",
];

let lastCronRunAt: string | null = null;
let cronTotalSent = 0;
let cronLastError: string | null = null;

app.post("/api/cron/auto-broadcast", async (req, res) => {
  const cronSecret = process.env.CRON_SECRET;
  if (cronSecret) {
    const auth = req.headers["authorization"];
    if (auth !== `Bearer ${cronSecret}`) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }
  }

  const { apiToken, groupId, siteName, promoUrl, botName, botSignature, hashtags, type } = req.body;
  if (!apiToken || !groupId) {
    res.status(400).json({ error: "apiToken and groupId are required in request body" });
    return;
  }

  const messageType: "alert" | "signal" = type === "alert" ? "alert" : "signal";

  try {
    let text: string;
    if (messageType === "alert") {
      text = formatAlertForWhatsApp({ siteName: siteName || "Signal Bot", botName: botName || "BOT", promoUrl: promoUrl || "" });
    } else {
      const market = MARKET_NAMES[Math.floor(Math.random() * MARKET_NAMES.length)];
      const contracts = ["UNDER 7", "UNDER 8", "OVER 2", "OVER 3"];
      const contract = contracts[Math.floor(Math.random() * contracts.length)];
      const digitMap: Record<string, string> = { "UNDER 7": "9", "UNDER 8": "9", "OVER 2": "1", "OVER 3": "2" };
      const strength = 85 + Math.floor(Math.random() * 14);
      text = formatSignalForWhatsApp({
        siteName: siteName || "Signal Bot",
        botName: botName || "BOT",
        promoUrl: promoUrl || "",
        market,
        contract,
        strategy: contract.startsWith("UNDER") ? "Second Least Digit" : "Over Digit Threshold",
        entryDigit: digitMap[contract] || "9",
        confidence: strength,
        hashtags: hashtags || "#TradingSignal #Signals",
        botSignature: botSignature || "Signal Bot",
      });
    }

    const cleanGroupId = sanitizeGroupId(groupId);
    const data = await whapiRequest("/messages/text", "POST", { to: cleanGroupId, body: text }, apiToken);
    if (data.error) throw new Error(typeof data.error === "string" ? data.error : data.error?.message || JSON.stringify(data.error));
    if (!data.sent && !data.message?.id && !data.id) throw new Error(typeof data.message === "string" ? data.message : "Send failed — check group ID and token");

    lastCronRunAt = new Date().toISOString();
    cronTotalSent += 1;
    cronLastError = null;

    res.json({ success: true, type: messageType, messageId: data.message?.id || "sent", totalSent: cronTotalSent });
  } catch (err: any) {
    cronLastError = err.message;
    res.status(500).json({ success: false, error: err.message });
  }
});

// ── Auto-broadcast configure: returns the two cron payloads ──────────────────
app.post("/api/autobroadcast/configure", (req, res) => {
  const { apiToken, groupId, groupName, siteName, promoUrl, botName, botSignature, hashtags, intervalMinutes } = req.body;
  if (!apiToken || !groupId) {
    res.status(400).json({ error: "apiToken and groupId are required" });
    return;
  }

  const host = req.headers.host || "your-app.vercel.app";
  const protocol = host.includes("localhost") ? "http" : "https";
  const cronUrl = `${protocol}://${host}/api/cron/auto-broadcast`;
  const interval = typeof intervalMinutes === "number" && intervalMinutes > 0 ? intervalMinutes : 2;

  const base = { apiToken, groupId, groupName, siteName, promoUrl, botName, botSignature, hashtags };
  const alertPayload = JSON.stringify({ ...base, type: "alert" });
  const signalPayload = JSON.stringify({ ...base, type: "signal" });

  res.json({ success: true, cronUrl, alertPayload, signalPayload, intervalMinutes: interval, cronPayload: signalPayload });
});

app.get("/api/autobroadcast/status", (_req, res) => {
  res.json({
    serverReachable: true,
    lastRunAt: lastCronRunAt,
    totalSentThisSession: cronTotalSent,
    lastError: cronLastError,
  });
});

app.post("/api/autobroadcast/disable", (_req, res) => {
  lastCronRunAt = null;
  cronTotalSent = 0;
  cronLastError = null;
  res.json({ success: true });
});

export default app;
